In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Student_Performance.csv")
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [3]:

df.replace({"Extracurricular Activities":{"Yes":0,"No":1}},inplace=True)
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,0,9,1,91.0
1,4,82,1,4,2,65.0
2,8,51,0,7,2,45.0
3,5,52,0,5,2,36.0
4,7,75,1,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,0,4,2,23.0
9996,7,64,0,8,5,58.0
9997,6,83,0,8,5,74.0
9998,9,97,0,7,0,95.0
9999,7,74,1,8,1,64.0

In [4]:
df.isna().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [5]:
inputs=df.drop(['Performance Index'],axis=1)
inputs

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,0,9,1
1,4,82,1,4,2
2,8,51,0,7,2
3,5,52,0,5,2
4,7,75,1,8,5
...,...,...,...,...,...
9995,1,49,0,4,2
9996,7,64,0,8,5
9997,6,83,0,8,5
9998,9,97,0,7,0
9999,7,74,1,8,1

In [6]:
output=df["Performance Index"]
output

0       91.0
1       65.0
2       45.0
3       36.0
4       66.0
        ...
9995    23.0
9996    58.0
9997    74.0
9998    95.0
9999    64.0
Name: Performance Index, Length: 10000, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test= train_test_split(inputs,output,test_size=0.8)
from sklearn.linear_model import LinearRegression

In [8]:
reg=LinearRegression()
reg

LinearRegression()

In [9]:
reg.fit(X_train,y_train)

LinearRegression()

In [10]:
y_predict = reg.predict(X_test)
y_predict

array([62.11210633, 27.42804228, 35.0382722 , ..., 47.59793802,
       67.25209414, 43.77707083])